### ISSUE TITLE
hardknott has a wrong u-boot-imx bbappend file

### ISSUE THREAD

**Issue by arunlee77** [SolidRun/meta-solidrun-arm-imx8#6]
[bbappend ](https://github.com/SolidRun/meta-solidrun-arm-imx8/blob/hardknott-imx8mp/recipes-bsp/u-boot/u-boot-imx_2021.04.bbappend) has the following

file://0009-Edit-u-boot-configurations.patch 

But there is no such file in u-boot.
Probably this is wrongly spelt and the correct name should be 

0009-Edit-imx8mp-solidrun-configuration-files.patch

**Comment by yazanShhade** [comment]
This is a split issue, you can overwrite the last comment to apply the correction.
Fixed - https://github.com/SolidRun/meta-solidrun-arm-imx8/blob/hardknott-imx8mp/recipes-bsp/u-boot/u-boot-imx_2021.04.bbappend
