### ISSUE TITLE
Impossible to get wifi connection 

### ISSUE THREAD

**Issue by juanmcc** [SolidRun/meta-solidrun-arm-imx8#9]
I'm trying to setting up wifi connection for Hummingboard Mate following these tutorials (there is not any information in any SolidRun webpage):

https://www.gumstix.com/community/support/faq/yocto-wifi/

https://www.digikey.lt/en/maker/projects/intro-to-embedded-linux-part-7-enable-wifi-networking-with-yocto/2e490a896a424a12b796ae60fef52937

But for my Yocto system it doesn't work.

My system is: Yocto Hardknott, with RealSense layer, building by imx-image-full.

When I'm doing ping, I receive "Network is unreachable".

How should I set up the wifi configuration?

Thank you so much.

**Comment by jnettlet** [comment]
This was fixed with the use of conman to connect to the AP.
